### ISSUE TITLE
Incorrect lens processing when the direction of ray propagation is negative.

### ISSUE THREAD

**Issue by vsnever** [PilulkinJr/zemax2raysect#10]
In Zemax, the sign of the surface curvature is determined relative to the current direction of the Z axis. If the ray propagates towards negative Z, then a surface that is concave with respect to the Z direction is convex for the ray and vice versa. This case is not currently handled for lenses, resulting in errors when converting the optical scheme from Zemax to Raysect. I have a fix for this and will make a pull request.

**Comment by PilulkinJr** [comment]
@vsnever, thank you.
Ray propagation is a complicated topic, which I am not completely confident about.
The current script worked well for examples that I have.
